### ISSUE TITLE
【QQ机器人】+【粉丝群管理】+【人数不限】

### ISSUE THREAD

**Issue by 2799615127** [ccyyycy/ycy#100]
主要利用酷q机器人提供服务，支持主流技术栈，使用编程技术管理粉丝群,禁言,禁词,踢人,聊天,推送天气,推送超越微博消息,分析微博数据,活跃群内气氛。会爬虫的小伙伴,可以根据机器人爬去一些超越图片,视频等等。
支持主流技术栈，需要一台服务器可以挂机器人，需要使用数据库(数据库技术我没想好用什么，mysql可以的)

**Comment by fzq5201314** [comment]
请注意发帖格式。[联系方式]

**Comment by hjsn101111** [comment]
有意，怎么联系你

**Comment by chenmychou** [comment]
有意，怎么联系你 qq895849097

**Comment by sunaowei** [comment]
有意 怎么联系？

**Comment by hushiping** [comment]
有意 qq2280343053

**Comment by 2799615127** [comment]
.

**Comment by SongZihuan** [comment]
如何联系？
