### ISSUE TITLE
【微信小程序】+【杨超越算命】+【人数不限】

### ISSUE THREAD

**Issue by guojun16** [ccyyycy/ycy#101]
做个高端大气上档次算命的小程序

有兴趣的大佬加q~

qq:864350301

**Comment by fzq5201314** [comment]
请注意发帖格式[编程语言，实现方式和开发环境等]
另:注意封建迷信！

**Comment by fzq5201314** [comment]
有封建迷信内容，暂时close。如果有其他的创意，请和组委会联系。
