### ISSUE TITLE
【平台社区】- 【超越月芽村】 -【手机app】-[3-5]-【微信1743171376】

### ISSUE THREAD

**Issue by panlx08** [ccyyycy/ycy#108]
这是一个村民聚集的村子，希望通过这个社区，让每位村民能够回村里看一看。村子主要地标及其功能：
村口小卖部：作为茶余饭后的聚集地，这是为大家提供实时八卦闲聊的地方，边看《哈哈农夫》，边来小卖部看看村民怎么说吧！（为了提供最真实的八卦环境，这里只保留最近十分钟的八卦消息）

杨村村委会:村民根据社区参与度获取超越金币，凭金币可竞选村委会成员。村委会成员可以在村委会公告栏上发布自己的《杨村日报》。

村委会公告栏:由当日村委会成员发布官方消息。

杨村超越艺术馆:这里有村委会布置的官方艺术馆，同时每个村民也可以申请一面墙，发挥自己的创造力，把自己最喜欢的超越图片或者自己创作的作品布置在这面墙上，邀请别的村民来参观吧。

杨村锦鲤池:位于杨村正中央，村民们可以把自己的愿望和心情写在石头人扔进锦鲤池里，其他村民可以查看或回复。

杨村游乐场:提供和超越有关的益智休闲小游戏。如大家来找茬、超越酷跑。

杨村后山小黑屋:为了维护杨村的和谐氛围，在以上地标功能发表言论连续被三名村民举报，即关进小黑屋，作禁言处理。

**Comment by fzq5201314** [comment]
请注意发帖格式[联系方式]

**Comment by fzq5201314** [comment]
[梦境之城.pptx](https://github.com/ccyyycy/ycy/files/3650256/default.pptx)
