### ISSUE TITLE
【游戏】+【寻找杨超越】+【web游戏/客户端游戏】+【5人】+ 找UI，node全栈🖖

### ISSUE THREAD

**Issue by iaminvictus1993** [ccyyycy/ycy#117]
### 内容

![jwt](https://user-images.githubusercontent.com/22359049/54005826-e3d79600-4195-11e9-9984-2f19a3165f57.gif)

核心玩法类似劲舞团操作，键盘霹雳夸啦一顿操作后按空格的快感。 [项目原型地址](https://github.com/iaminvictus1993/findycy)    [在线试玩地址](http://iaminvictus1993.gitee.io/findycy/)

###  目标
能够提交作品，拿到巧克力吃

###  队友
前端、UI、找图、找音乐、音频图片后台处理

### 联系方式

![qq群 ](https://user-images.githubusercontent.com/22359049/54005503-a7576a80-4194-11e9-9dd9-a876141edeff.png)

**Comment by p6vital** [comment]
报名。前端 node 爬虫都可以

**Comment by iaminvictus1993** [comment]
流产了.........
