### ISSUE TITLE
【平行世界】超越村 - 真实存在于平行世界的村落。【人数 : 7+人】【联系方式 : i@xingcheng.me】

### ISSUE THREAD

**Issue by follyxing** [ccyyycy/ycy#133]
# 致力于打造第一个平行世界中的真实的村落

> 概念简述：平行于真实世界的村落-**超越村**。本项目致力于将超越村打造为第一个网络中存在的真实世界，村内拥有独立的经济体系，法律体系等，入村的村民需要申请超越村绿卡。超越村里的每一位村民，在真实世界之外，拥有超越村村民的身份。村民不限定国家及地区，拥有绿卡即为超越村村民。

## 技术需求
> 本项目主要侧重于区块链方向

1.区块链部分基于Ethereum平台
2.服务器端 (JAVA , GO , Lua)
3.前端 (Vue.js)
4.移动端 (iOS Android ReactNative)

## 人员需求
* UI设计师
* 前端工程师
* 后端工程师
* 移动端工程师
* 产品经理(区块链方向)
* 文案策划
* 律师

## 项目周期 
本项目将持续迭代。

## 其他
成为超越村村民，将拥有诸多权利。例如：
* 投票权 - 决定杨超越部分选择
* 村民优惠卡 - 村民在真实世界中消费享受折扣
等等 ...

**Comment by follyxing** [comment]
有什么意见建议，大家场所预言~

**Comment by fzq5201314** [comment]
请注意格式【人数】【联系方式】

**Comment by follyxing** [comment]
> 请注意格式【人数】【联系方式】

改好了 ~

**Comment by Kylin93CN** [comment]
比较有兴趣。
本人web前端，react+RN都有项目经验，vue也会点。

**Comment by a1084487400** [comment]
Java，2年。

**Comment by weizheshen** [comment]
Java，1年，有兴趣。

**Comment by JasonBournehu** [comment]
java 三年  前端也能写一些

**Comment by lofbat** [comment]
java，1年

**Comment by yukunshang** [comment]
java 和vue 有涉及过 区块链也了解过拜占庭将军等问题 对此项目感兴趣

**Comment by myxh** [comment]
Android 2年，求大佬带队

**Comment by sxin0** [comment]
项目地址在哪里.
