### ISSUE TITLE
【幽默创意向】+【超越狂扁小朋友】+【微信小游戏】+【5人】+【邮箱hangge_666@163.com】

### ISSUE THREAD

**Issue by hangge666** [ccyyycy/ycy#134]
**我们与熊孩子的战争一触即发，熊孩子的战火已经烧到了家门口，还好我们的元气女斗士超越来到了战争前线，然后我们站在她的身后，欣赏这战争的艺术~**

1. 开发平台，在小游戏平台开发，不涉及后台，重点是把画面做好，但是不能直接用超越MM图片哦，侵犯他人的事情我们不弄，目标是用有趣的场面博得超越妹妹的喜爱。
2. 游戏类型：横版格斗类，无关卡，怪预设，一个boss，一次通关。
3. 人员搭配，我本人是技术还不过硬的小程序员，这次就主攻策划、协调、开发，再加上开发一位，美术两位，还需要一位大佬管理开发、技术分析、版本控制，这位应该就是我们的核心领导了。

请联系我好嘛？

**Comment by tabeworks** [comment]
兄dei，你是敌营的吗，这创意的对手角色别踩线 小心招黑

**Comment by hangge666** [comment]
> 兄dei，这创意的对手角色别踩线 小心招黑

您是误会了，我并没有恶意，我本打算是将小孩子描绘为熊孩子的，我认为现在熊孩子还是属于坏人群体，所以还是可以将他们放在对立面。
不过我也觉得这个题材非常容易引起误会，并且还没有找到可靠的小伙伴，如果您的团队还缺少开发或者策划，可以联系我哈
