### ISSUE TITLE
【游戏】 + 【杨超越漂流记】 + 【unity3d/微信小程序】 + 【人数待定】

### ISSUE THREAD

**Issue by 1163710231** [ccyyycy/ycy#146]
类似于饥荒类生存游戏和农场经营游戏结合的小游戏；
背景：超越流落至一个荒岛，在荒岛上收集资源和食物，种植植物、驯养动物以生存下去；
用u3d做成独立游戏，或者做成微信小程序游戏以便于推广；
具体游戏细节大家一起讨论；
QQ：570232054；微信：Zhang_rui_zhuo；

**Comment by 1163710231** [comment]
一起商量

**Comment by lixiang1991** [comment]
这个想法不错，我有兴趣试试，加你qq了
