### ISSUE TITLE
[web]+[watchYcy]+[opencv]+[3]

### ISSUE THREAD

**Issue by regaliastar** [ccyyycy/ycy#153]
## 描述
[step 1]
start ->
用户将图片传递到服务器 -> 
服务器判断图片中是否有杨超越 ->
返回true/false
[step 2]
修改返回值，返回图中杨超越的抠图
## 难易度
图像识别处理是相当成熟的技术，为了实现该方案，只需要调用API，并且准备大量训练集。难度相对简单且切合题意

**Comment by chenrui520** [comment]
需要web端吗

**Comment by fzq5201314** [comment]
请注意格式【联系方式】
