### ISSUE TITLE
【游戏】+【杨成计划】+【微信小游戏】+【5人】+【微信：l476298818/QQ：476298818】

### ISSUE THREAD

**Issue by LKCheng** [ccyyycy/ycy#164]
初步想法：结合QQ宠物和阴阳师打造一款养成类的小游戏
实现方式：微信小游戏，游戏引擎cocos2d 
最终目标：实现一款完整的小游戏

具体游戏细节大家一起讨论：
本人担任前端和策划
数据存储以及传输部分将用node作为后端接口来使用（本人可以写）
现需要2名美术，2名前端；

**Comment by lyndonk** [comment]
？？、

**Comment by lyndonk** [comment]
兄弟你的这个还做吗
