### ISSUE TITLE
【游戏】+【贪吃超越吃篮球】+【h5+js/h5】+【1-5】+【微信：programluo】

### ISSUE THREAD

**Issue by lusson-luo** [ccyyycy/ycy#169]
类似贪吃蛇的杨超越吃篮球的游戏
之前写过贪吃蛇游戏，核心逻辑存在
需要前端做手机端适配（重要）
需要美工做图（一般）
需要产品做游戏设计（有更好）

现在已有两名开发人员

**Comment by programluo** [comment]
现在只缺一名前端做手机端页面适配
