### ISSUE TITLE
【数据分析】+【自动分析微博超越粉丝的公开信息】+【python后台】+【5人】+【qq2910650466】

### ISSUE THREAD

**Issue by west789** [ccyyycy/ycy#170]
暂定微博为平台，爬取超越粉丝的人员构成，各个分布状态，利用pandas等python分析库，进行数据处理和展示。
爬取数据
清理数据，去重复，分词
按序存储
生成图表

**Comment by HankChow** [comment]
python 后台

**Comment by programluo** [comment]
我会用java写爬虫，爬过CSDN的用户行为数据做分析，可以参加吗

**Comment by west789** [comment]
> python 后台



> 我会用java写爬虫，爬过CSDN的用户行为数据做分析，可以参加吗？我把爬的数据放到json文件，你们再去做分析



> 我会用java写爬虫，爬过CSDN的用户行为数据做分析，可以参加吗？我把爬的数据放到json文件，你们再去做分析

qq群：294471657

**Comment by west789** [comment]
> 我会用java写爬虫，爬过CSDN的用户行为数据做分析，可以参加吗？我把爬的数据放到json文件，你们再去做分析

qq群：294471657

**Comment by west789** [comment]
> python 后台

qq群：294471657
