### ISSUE TITLE
【Flutter 锦鲤 App】+ 瓶子聚聚战队 +【缺三人, ios flutter】+【群号:917514893】

### ISSUE THREAD

**Issue by yikwing** [ccyyycy/ycy#172]
各位大大 快用flutter写程序吧 ! 推广ycy和 flutter

**Comment by moucashi** [comment]
图集类APP 网络爬图 AI换脸杨超越!

**Comment by zxj5470** [comment]
可还行

**Comment by power721** [comment]
禁止AI换脸！

**Comment by yikwing** [comment]
你们别出馊主意  大概ui长这样
![image](https://user-images.githubusercontent.com/20245290/54017661-a557d080-41c1-11e9-880a-634e43a2aa69.png)

**Comment by LittleChuan** [comment]
iOS QQ：248254119

**Comment by hjsn101111** [comment]
android的 会点 ios 自学过flutter 需要联系

**Comment by yikwing** [comment]
想一起学习flutter并做这个项目的可以加群 [917514893]

**Comment by zxj5470** [comment]
群都加不了（滑稽
