### ISSUE TITLE
【工具/养成】+【养超越】+【微信小程序】+【5人】+ 【满人】

### ISSUE THREAD

**Issue by D1N910** [ccyyycy/ycy#174]
## 口号
一起养超越(ﾟ▽ﾟ)/

## 玩法内容
 * 用户通过「签到」记录自己的运「动数据」从而「喂养超越」
* 不同阶段的超越可以有不同的东西产出，比如集卡用的“卡片碎片”，“超越加油声音”

## 成员需求
* 擅长使用ai绘制人物的UI设计师同学 （已满）

* 对于微信鉴权有过应用的后端同学  （已满）
* 有制作后台管理系统经验，也会一些小程序的前端同学（已满）

## 预计排期

* 即日-3月12日 组建团队，同时进行第一版的高保真原型图，可能的对应ui图第一稿的制作
* 3月12日-3月22日（10天） 前后端进行开发，完成第一版核心需求（功能不用太多，优秀就好）
* 3月22日-3月24日（2天）集中测试
* 3月24日-3月27日 （3天）项目发布落地，产出相关产品文档

## 报名方式
* 底下回复对应位置占位，留下自己的联系方式（建议base64），我会在60min内联系大佬
* 也可以联系我 QQ： MjYwMDAyMzMw
* 超越杯编程大赛群 D1n910

## 组织者介绍
* 负责前端和产品，会后端
* 前端技术栈 微信小程序、Vue 、React，移动端和PC端均有过开发经验
* 对于参与比赛和组织团队协作有经验，获得过腾讯微信高校小程序开发者大赛华南赛区一等奖（再进一步就全国啊啊啊）
* 从创期开始关注超越的男粉丝一枚

**Comment by power721** [comment]
base64比较秀

**Comment by liufeics** [comment]
养成？很优秀啊

**Comment by D1N910** [comment]
> base64比较秀

主要是为了防止搜索引擎检索，你懂的

**Comment by D1N910** [comment]
@liufeics my boy，月♂吗

**Comment by tankda** [comment]
偷电瓶车养

**Comment by D1N910** [comment]
![](https://ws1.sinaimg.cn/large/006ES7aSgy1g0vijqzvhvj30ku112tpk.jpg)

**Comment by D1N910** [comment]
@tankda 运动养

**Comment by alanleung2017** [comment]
已报名23333

**Comment by yue1173** [comment]
sketch画人物可以吗？。。可以的话想参加

**Comment by D1N910** [comment]
@yue1173 嗷嗷嗷嗷嗷嗷，可以鸭，超过3h才回复很抱歉QAQ（因为周末刚起床orz

**Comment by D1N910** [comment]
止步于14.
