### ISSUE TITLE
【GAN/CV】+【ycy dance now】+【python】+【满人】

### ISSUE THREAD

**Issue by Gword** [ccyyycy/ycy#177]
### Motivation
训练GAN（生成对抗网络）生成ycy跳舞视频，帮助不会跳舞的ycy跳舞！

### Pipeline
1. pose detection
2. global pose normalization
3. mapping from normalized pose stick figures to the target

**Comment by yasongxu** [comment]
这个nb啊

**Comment by BigBugGrow** [comment]
人人皆为舞王 – Everybody Dance Now 的 PyTorch 实现

**Comment by BigBugGrow** [comment]
人人皆为舞王 – Everybody Dance Now 的 PyTorch 实现
https://www.pytorchtutorial.com/everybody-dance-now/

**Comment by BigBugGrow** [comment]
已有开源实现
人人皆为舞王 – Everybody Dance Now 的 PyTorch 实现
https://www.pytorchtutorial.com/everybody-dance-now/
paper:《Everybody Dance Now》https://arxiv.org/abs/1808.07371

**Comment by Gword** [comment]
> 已有开源实现
> 人人皆为舞王 – Everybody Dance Now 的 PyTorch 实现
> https://www.pytorchtutorial.com/everybody-dance-now/
> paper:《Everybody Dance Now》https://arxiv.org/abs/1808.07371

是有模型 但是要用ycy的数据重新训练XD

**Comment by Gword** [comment]
## More Details
* 本项目实现了一种基于pix2pixHD生成对抗网络和时域空间平滑的运动转移方法，用户给定一段跳舞的源视频，我们可以该表演动作转移到另一主体——杨超越，从而生成杨超越完成该舞蹈的视频。我们使用姿势检测作为用户舞蹈和杨超越舞蹈之间的中间表示，学习从姿势图像到杨超越主体外观的映射。为了完成这项任务，我们将项目流程划分为三个阶段：姿态检测、全局姿态归一化以及从标准化姿态图到杨超越图像的映射。在姿态检测阶段，我们使用SOTA姿势检测器来对定自源视频每一帧创建姿态图。全局姿态标准化阶段考虑了源体姿态和杨超越姿态的形状与镜头位置之间的差异。最后，我们设计了一个基于pix2pixHD生成对抗网络的端到端系统来学习从标准化的姿态图到用于对抗训练的杨超越的图像的映射。为保证结果视频的真实性，我们结合了视频时域空间的平滑方法和真实感的面部合成方法对视频结果进行优化。

**Comment by JunjieW** [comment]
Adding demo: https://m.bilibili.com/video/av47951973.html

Great job :+1

**Comment by Gword** [comment]
> Adding demo: https://m.bilibili.com/video/av47951973.html
> 
> Great job :+1

这个视频不是我们发的 已让up主下架
