### ISSUE TITLE
-1

### ISSUE THREAD

**Issue by 3047209075** [ccyyycy/ycy#179]
0

**Comment by MashiMaroLjc** [comment]
我个人不太想把deepfakes换脸或GAN用在超越身上，因为不是所有人都是君子。

虽然其他明星的deepfakes已经有了，但基本还是圈子内的人搞的，而且视频在国外那****hub上。但这次比赛的关注有些大，我不想让deepfakes这件杀器出圈。。。。。

美颜可以，deepfakes我真的建议慎重，可能有不太好的后续影响。
