### ISSUE TITLE
！【组队需求格式】！

### ISSUE THREAD

**Issue by fzq5201314** [ccyyycy/ycy#18]
请大家在issue发表组队需求时参照本文

标题：【大致方向】+【名称】+【相关技术/平台】+【组队所需人数】
例子：【游戏】+【村民月芽大战黑子小游戏】+【微信小程序】+【3人】
内容：写明本项目的最终目标，实现方式，初步想法，以及联系方式/群内ID等
回复：如果有任何想法，或者想要加入，可进行回复。

不符合格式的帖子会通知大家修改一下的。

**Comment by junxun66** [comment]
【游戏】【火箭少女自走棋】【unity3d】【3人】

**Comment by GudthliyaHonor** [comment]
尝试尝试。

**Comment by overbearingceofirst** [comment]
我只会写静态页面啊哈哈哈哈，请问哪个大佬需要啊

**Comment by yangliyang5544** [comment]
只会写if else for 哈哈。围观

**Comment by peter-peng** [comment]
java后台 有需要的拉一下

**Comment by sacrohu** [comment]
加入
