### ISSUE TITLE
【工具】+【超越好习惯】+【微信小程序】+【3人】+【QQ：366869822】

### ISSUE THREAD

**Issue by vlong5461** [ccyyycy/ycy#183]
一款自律的工具类小程序，可以添加习惯计划，添加礼物。完成好习惯计划，获取心心，心心兑换礼物。
本人可以开发小程序。
还差1名UI，把小程序做漂亮。

期待您的加入。QQ：366869822

**Comment by yue1173** [comment]
我想应征美工 weiboyuezheng

**Comment by SongZihuan** [comment]
还在吗
