### ISSUE TITLE
关于在超话抽奖又用不起微博抽奖平台的需求

### ISSUE THREAD

**Issue by EvilBT** [ccyyycy/ycy#19]
例如这条[微博](https://weibo.com/6426575844/HjunREn8H?filter=hot&root_comment_id=4346464161382134&type=comment#_rnd1551769367226)
这些想抽奖给评论者的人，只能依靠人工抽奖（我也不知道他怎么抽），弄这个感觉不难。

**Comment by fzq5201314** [comment]
随机数生成器+@指定评论？ 挺有实际意义的

**Comment by hejujie** [comment]
想到的步骤是：
- 首先把对应的评论趴下来。
  - 输入可以是当前微博的链接。
  - 输出是所有的评论内容、发布人以及时间。
- 然后再使用随机数选择一条。
  - 根据上面得到的信息：例如固定句式，限定时间进行初步筛选。
  - 随机选择其中一条，输出对应的发布人。

**Comment by daiwh** [comment]
抽奖这种事情缺少监管，应该不好搞，没法让大家信服

**Comment by happyjared** [comment]
idea不错。。有意
