### ISSUE TITLE
【游戏】+【超越象棋——保护我方杨超越】+【web应用】+【独立制作，需要美术音效等支持】+【tingersure@gmail.com】

### ISSUE THREAD

**Issue by TingerSure** [ccyyycy/ycy#191]
### 我们想做什么？

一款棋类游戏，火箭少女们团结一致，“保护我方杨超越”！

### 我们需要什么样的伙伴？

- 美术支持
- 音效支持
- 创意支持
- 运营支持
- 编码支持

### 怎么联系我们？

邮箱 <tingersure@gmail.com>

### 游戏规则是怎样的？

![wechatimg20](https://user-images.githubusercontent.com/7395204/54017963-80179200-41c2-11e9-9871-90b16c001702.jpeg)

![wechatimg19](https://user-images.githubusercontent.com/7395204/54009698-d4147d80-41a6-11e9-9b05-476ec7bfd494.jpeg)

![wechatimg18](https://user-images.githubusercontent.com/7395204/54009840-5dc44b00-41a7-11e9-86ae-1f107ab7c69c.jpeg)
- 超越象棋活动的场所位于一个平面内的矩形区域中，称为 __棋盘__ ；
- 在棋盘上，有五条互相平行、依次排布、相邻距离相等的直线，称为 __横线__ ，从“A”开始依次以英文字母表示，相邻横线的距离为 __一__ ，单位为 __格__ ；
- 在棋盘上，另有九条互相平行、依次排布、相邻距离相等、与任意横线垂直的直线，称为 __纵线__ ，从“1”开始依次以阿拉伯数字表示，相邻纵线的距离与相邻横线的距离相同；
- 所有横线与纵线的交点，称为 __落点__ ；
- 如果两个落点的横线和纵线距离有且仅有一个为一格，其余全为零格，则称这两个落点 __相邻__ ；
- 超越象棋活动使用的圆饼形刻字或印花道具，称为 __棋子__ ；
- 两个棋子之间的关系分为 __友方__ 和 __非友方__ ；
- 棋子分为 __红色__ 和 __黑色__ ；
- 红色棋子共十一枚，互为友方棋子，包括“__鲤（E1）__”、“__孟（D1）__”、“__宣（E2）__”、“__段（C1）__”、“__Y（D2）__”、“__七（E3）__”、“__傅（B1）__”、“__宁（C2）__”、“__S（D3）__”、“__虹（E4）__”、“__婷（C3）__”；
- 黑色棋子共十一枚，互为友方棋子，包括“__花（A9）__”、“__岐（B9）__”、“__仪（A8）__”、“__娟（C9）__”、“__鸭（B8）__”、“__赖（A7）__”、“__菁（D9）__”、“__宁（C8）__”、“__桑（B7）__”、“__洁（A6）__”、“__婷（C7）__”；
- “鲤”和“花”两枚棋子分别称为红色、黑色棋子的 __胜负子__ ，为表区分，其他棋子称为 __普通棋子__ ；
- 棋子能且仅能放置在落点上；
- 棋子可以在不同落点上移动；
- 棋子移动到与原落点相邻的落点称为棋子的 __滑步__ ；
- 棋子移动到与原落点横线和纵线距离都为一格的落点称为棋子的 __斜步__ ；
- 棋子滑步和斜步都称为棋子的 __基本移动单元__ ，是棋子最小的，不可再分的移动方式，移动开始的落点称为基本移动单元的 __源落点__ ,移动结束的落点称为基本移动单元的 __目标落点__ ；
- 棋子通过一个或一个以上连续基本移动单元完成的移动称为棋子的一次 __行棋__ ，每一个基本移动单元的目标落点按先后顺序构成的有序集合称为此次行棋的 __路径__ ，第一个基本移动单元的源落点称为此次行棋的 __源落点__ ，最后一个基本移动单元的目标落点称为此次行棋的 __目标落点__ ，除去行棋的目标落点外的行棋路径称为行棋的 __途径路径__ ；
- 如果棋子行棋的途径路径上有其他棋子，则此行棋不可行；
- 如果棋子行棋的目标落点上有友方棋子，则此行棋不可行；
- 如果棋子行棋的目标落点上有非友方棋子且途径路径上没有其他棋子，则此行棋可行，同时此非友方棋子淘汰；
- 如果棋子行棋的路径上没有其他棋子，则此行棋可行；
- 棋子被规则允许进行的行棋方案称为其遵循的 __行棋规则__ ；
- 由且仅由一个滑步的构成的行棋规则，称为 __滑步__ 行棋规则；
- 由一个滑步和一个斜步按序构成且目标落点和源落点不相邻的行棋规则，称为 __马步__ 行棋规则；
- 如果棋子在其行棋规则下拥有至少一个可行的行棋，则称其处于 __活跃__ 状态；
- 如果棋子在其行棋规则下没有任何可行的行棋，则称其处于 __困毙__ 状态；
- 胜负子遵循滑步行棋规则；
- 普通棋子遵循马步行棋规则；
- 超越象棋由两位对弈者进行对弈，分别执黑棋和红棋，执红先行，交替行棋；
- 当回合交替至其中一位对弈者时，若此对弈者的胜负子已经被淘汰或者所有棋子均处于困毙状态，则判其负，此局对弈结束。

**Comment by fanpeii** [comment]
厉害了，mark一下

**Comment by jackluson** [comment]
需要前端吗?

**Comment by TingerSure** [comment]
> 需要前端吗?

开发齐了，抱歉
