### ISSUE TITLE
我这里有两个项目提议（我本人不会编程，只能提供想法和建议）

### ISSUE THREAD

**Issue by kay8baby** [ccyyycy/ycy#196]
相当有难度的项目。

第一个：有关驾驶证考试的闯关类APP或页游。
考驾照的人都在学习过程中对看书背题感到乏味，而且记不住，我觉得可以弄这么一款APP，有关驾考的一款APP，两种方案，一个相对简单，一个相对复杂，或者两者可以结合。第一种，答题闯关模式的APP，利用动画模式来做，例如前方有交警打手势，出现几个答案，答对了有奖励，答错了有惩罚(大富翁游戏模式的奖罚机制可以学习一下，如开罚单，超速撞车进医院等等，APP里的主人公或许超越可以客串一下？让超越参与录音也不错)

第二个：针对小孩子的游戏类APP，就是让孩子们可以在游戏中也能够学习并锻炼自己，这个APP针对年龄小的儿童，游戏中可以穿插数学题或汉语拼音等问题，机制与上一个相同。

这项目需要有经验的人来带领，有兴趣的可以加QQ527729745，备注：杨超越杯变成大赛。
如果人多的话我会建群交流

**Comment by fzq5201314** [comment]
所有项目都要和杨超越相关哦，麻烦更改标题和内容。
没更改会被关闭issue哦
