### ISSUE TITLE
【生活】+【村芽土地 APP】+【Android + iOS/ Flutter/ ReactNative + Go/ Java/ PHP】+【4-6人】

### ISSUE THREAD

**Issue by york1996** [ccyyycy/ycy#204]
**村芽土地 APP** 
大型交友 APP，甚至相亲！配对成功可获 YCY 祝福一份！

idea：https://github.com/ccyyycy/ycy/issues/204#issuecomment-470963912

**Comment by zhangxh1023** [comment]
占坑 举手🙋‍♂️🙋‍♂️

**Comment by wwcy** [comment]
我也占一个坑 #

**Comment by OldFarHigh** [comment]
算我一个吧

**Comment by TrainTsang** [comment]
+1

**Comment by saboluo** [comment]
+10086  java+前端

**Comment by shijian123** [comment]
占坑，熟练iOS，不过想练练flutter😀

**Comment by york1996** [comment]
想法如下：
结合最近社交软件市场，我们推出一款语音 + 视频社交 APP，先通过创建房间/加入房间操作，一个房间可群体聊天（6-8人）、1对1聊天（2人）两种模式，创建房间时仅可以语音通话，双方/多方语音通话10分钟后（具体时间待定）即可开始邀请开启视频，开启社交新玩法。大家可以同时在看某个电视节目（e.g. 创造101嘻嘻嘻嘻）时一起加入一个房间吹牛逼，可以受到委屈时语音倾诉。产品除数据库为了遵循相关法律法规有实名手机信息外不公布任何个人信息，匿名社交市场马上开启！

**Comment by fzq5201314** [comment]
请注意格式【联系方式】

**Comment by mrchentop** [comment]
Android 占坑

**Comment by myxh** [comment]
Android占坑

**Comment by MiZuHaSi** [comment]
Android+Flutter占坑

**Comment by yikwing** [comment]
Android+Flutter占坑

**Comment by LH-Hadoop** [comment]
java+前端，占个坑，请问下怎么加入团队

**Comment by zhangtongshuai** [comment]
flutter前端，占坑

**Comment by york1996** [comment]
me@york1996.com
可以加扣扣，可以群里搜🌚

**Comment by OldFarHigh** [comment]
yangzhenl@126.com java 群里有

**Comment by wangxinhx** [comment]
php +golang  占个坑，请问如何加入

**Comment by hackxingxing** [comment]
golang

**Comment by york1996** [comment]
加班加到没顾到这里，对各位表示兴趣的同学们表达歉意，close
