### ISSUE TITLE
【网站】+【超越信息系统】+【爬虫】+【node,puppeteer,vue】+【qq:718091951】

### ISSUE THREAD

**Issue by guyixn** [ccyyycy/ycy#217]
### 主要内容:
通过 **爬取ycy** 的公开信息,以及最新的网上动态

 1.把最新的信息(图片,视频等)展示在主页上,利用AI把最有意思,最好玩的评论也展示出来

 2.然后分析,通过ycy的卡通人物( **需要一个webgl大神,或H5大神** )来展示ycy的心情指数,以及粉丝的热情指数

 3.然后把爬取的超越的信息绘制成一个时光机

### 主要的技术：
puppeteer+vue(/jq)+nodejs+mongodb+AI(时间有限,使用第三方接入)

**Comment by ch3nl00ng** [comment]
Hello 我是刚才在QQ上和你聊在heroku上建redis的那个人。我qq号突然登不了了。你微信多少呀？我可以加吗？

**Comment by HyattJobs** [comment]
> Hello 我是刚才在QQ上和你聊在heroku上建redis的那个人。我qq号突然登不了了。你微信多少呀？我可以加吗？

可以, WX:jiaruaiyouliuxing

**Comment by zkna** [comment]
已过期
