### ISSUE TITLE
【通用打投数据记录站】+【web平台】+【2人】

### ISSUE THREAD

**Issue by nonight** [ccyyycy/ycy#22]
- 简介：

通用的打投数据追踪系统，为每次的打投活动，提供数据记录支持
例如马上要进行的猫眼公益打投

- 基本架构：

数据爬取 -》存储入库 -》通用数据展示
数据展示部分可以提供每小时，每天，每周几个纬度的 数据曲线
每次有不同的打投任务，只需要新增job, 同时开发新的爬取逻辑

- 人员：

数据爬取+入库存储   1人
后端读取数据+前端ui  1人

- 开发周期：

一周内

**Comment by EVO-smj** [comment]
爬虫+sql这里可以，如果只是少量的数据处理和用django简单展示也可以做，爬取打投的话数据量不大，而且展示页面反爬机制应该也不难，主要是定时爬取入库，然后读取可视化就行了。不过个人感觉这个项目意义主要是看看打投数据有没有异常变化或者某个维度出问题吧。

**Comment by power721** [comment]
我已经有数据监控网站了

**Comment by nonight** [comment]
https://ycy.har01d.win/
看到已经有数据站点了，不用重复开发了
