### ISSUE TITLE
【网站+小程序】+【越光·社交】+【vue/mpvue/django/drf】+【不限】+【缺人啊q群：18861872】

### ISSUE THREAD

**Issue by pangdjango** [ccyyycy/ycy#221]
### 技术栈
**前端**：vue/mpvue/uni-app 任意熟练者皆可。
**后端**：django/drf
### 快上车啦O(∩_∩)O
1.  能调整出足够的空余时间、有使用vue开发过PC端网站以及微信小程序的大触童鞋。
2.  熟练掌握django/drf开发与上线部署，且有能调整出足够的时间一起搞的童鞋大触。
4. 没有足够的时间，有兴趣来帮帮忙也是欢迎的啊
### 《越光》项目计划书
**应用类型**：PC网站+微信小程序
**项目类型**：泛社交类论坛。
**功能说明**：

1. 用户通过微信登录后，共享自身位置，小程序和网站首页中会显示地图，用户所在位置会亮起一个光点，男性用户为蓝色，女性用户为粉色。用户附近的村民和月牙越多，地图就会越亮。30天不登录就光点即黯。

2. 在小程序和网站首页有一个像中学附近奶茶店里那样的许愿墙模块，每个用户都可以将自己的愿望写上去，写上愿望的时限（比如，今年要陪男友去看杨超越的演唱会，时限今年年底），如果在时限之内实现了，就点【实现了】按钮，这个愿望就会进入个人中心的【幸运】栏下，如果在时限之内没有实现，就点【没实现】按钮，这个愿望就会进入个人中心的【遗憾】栏下。

3. 用户可以看附近的用户的愿望，也可以随机在全国的许愿墙里查看愿望，可以评论愿望：“他不爱你”或者“我帮你实现你未完成的愿望吧。”

4. 首页许愿墙可以置顶杨超越发布的愿望，管理员也可以置顶比较有公益性质的愿望。

5. 杨超越的账号拥有“越光”的最高权限，可以随时冻结任何用户以及解冻一个用户，可以随时向所有用户发私信通知。

6. 杨超越的账号拥有“越光”的最高权限，可以随时冻结任何用户以及解冻一个用户，可以随时向所有用户发私信通知。

**目标用户**：为杨超越的粉丝搭建一个没有黑粉和路人，只有村民和月牙的绝对领域，只要是杨超越的粉丝，不分年龄段都是目标用户。

![1-01](https://user-images.githubusercontent.com/42256679/54065008-873bb000-4255-11e9-92be-e6d5c5f5fe2f.jpg)

**Comment by fzq5201314** [comment]
争议过大，close
