### ISSUE TITLE
【游戏】+【超越滑机大战】+【编程猫】+【2人】+【满员】

### ISSUE THREAD

**Issue by epeiuss** [ccyyycy/ycy#236]
本次参加这个比赛，我们要做出一款滑机大战的游戏。这个名字可是废了我一番苦心。滑机=滑稽，因为全部都是杨超越啊，敌人杨超越，弹幕杨超越，连自己都是杨！超！越！之所以是“机”是因为很像飞机大战。
人员已满，开始策划了，敬请期待！！！

**Comment by Queenieye** [comment]
很棒呀

**Comment by yulimfish** [comment]
实时进度：本作品已进入ui制作阶段
