### ISSUE TITLE
【视频直播拍卖平台】+【星闪】+【APP】+【越多越好】

### ISSUE THREAD

**Issue by Secondidoit** [ccyyycy/ycy#242]
产品描述：
明星通过“星闪”视频直播把用不到的物品拍卖出去，拍卖所得用于公益活动。

要点说明：
（1）	每一个标的拍卖限时5分钟，5分钟内出价最高者得，无出价则流拍
（2）	拍卖最高价不得高于10000元，避免非理性竞拍
（3）	拍卖所得95%用于公益活动，5%用于平台运营
（4）	公益活动款项支出每一笔均进行明细公示，并聘请公证部门公正

有兴趣请加QQ群：319621360

**Comment by fzq5201314** [comment]
与杨超越无关，close，不好意思。
