### ISSUE TITLE
为什么qq群加不了

### ISSUE THREAD

**Issue by egoistor** [ccyyycy/ycy#250]
惊了.jpg

**Comment by fzq5201314** [comment]
你好，请问是哪个群？

**Comment by egoistor** [comment]
> 
> 
> 你好，请问是哪个群？

956848519这个群

**Comment by egoistor** [comment]
> 
> 
> 你好，请问是哪个群？

还有招美工设计的群也找不到，就很怪

**Comment by fzq5201314** [comment]
这个群目前是能能够搜索到的；

**Comment by fzq5201314** [comment]
[https://jq.qq.com/?_wv=1027&k=5bZW930](url)

**Comment by fzq5201314** [comment]
美工设计群在群公告文件中，close issue
