### ISSUE TITLE
前端一枚，会vue,angular,flutter的app开发，h5,小程序，都可以，求组队啊，+QQ862752683

### ISSUE THREAD

**Issue by zhangtongshuai** [ccyyycy/ycy#255]
会vue,angular,flutter的app开发，h5,小程序，都可以，求组队啊，+QQ862752683

**Comment by lminggang** [comment]
后端，java python 都可以，服务器可以放心交给我。前端 vue element-ui也行 求组队 +QQ2176660382

**Comment by yikwing** [comment]
移动端 flutter + android   后台 java + python  网页 React vue  组队

**Comment by fzq5201314** [comment]
组队可以加入大赛QQ群，956848519
