### ISSUE TITLE
【Shell屏保】+【Linux屏保】+【Python】+【2人】+ 【qq群号：778618351】

### ISSUE THREAD

**Issue by chenxin199261** [ccyyycy/ycy#266]
## 期待效果
当Linux shell的不活跃一段时间后，屏幕保护开启。给Linux端程序工作者注入好运气。
屏保内容可以是
1. 黑客帝国代码流形式，显示杨超越的语录。（简单版本）
2. 字符动画。（复杂版本）

## 技术难点
1. 代码流效果实现。
2. 字符动画与屏幕尺寸适应。

## 你会学习到：

1. Python定时启动
2. 一些炫酷效果

## 实现

本人只会Python,C, Fortran. 必须在Linux平台下开发。  

## 联系方式
请直接加群

**Comment by sxlgkxk** [comment]
人为创造需求:neutral_face:
还是往花里胡哨整吧（python有库，node更多），大概没人需要shell屏保的吧:neutral_face:

**Comment by sxlgkxk** [comment]
是个好方向诶，这个算是最代码范的了（越是黑窗口越'高级'）
最后把效果剪成短片供赛后剪辑使用

**Comment by sxlgkxk** [comment]
![image](https://user-images.githubusercontent.com/21279752/54087327-bacd2600-438c-11e9-989b-183a961f52d6.png)
随便找了段代码, 改成从文本读入就vans了
代码占地不贴了, [matrix_animation](https://github.com/sxlgkxk/025-matrixlike_shell_Animation)
