### ISSUE TITLE
后端Python Java都可以，服务器端放心交给我，还有没有缺人的，时间无线 +WX 18710002395

### ISSUE THREAD

**Issue by lminggang** [ccyyycy/ycy#271]
后端Python Java都可以，服务器端放心交给我，还有没有缺人的，时间无线 +WX 18710002395

**Comment by jiangbdkbk** [comment]
可以爬数据么？我有个项目，刚发，你可以看看呀https://github.com/ccyyycy/ycy/issues/277

**Comment by fzq5201314** [comment]
请按格式提交

标题：【大致方向】+【名称】+【相关技术/平台】+【组队所需人数】
例子：【游戏】+【村民月芽大战黑子小游戏】+【微信小程序】+【3人】
内容：写明本项目的最终目标，实现方式，初步想法，以及联系方式
