### ISSUE TITLE
【游戏】+【挖机jw倒闭了】+【微信小游戏】

### ISSUE THREAD

**Issue by milledragon** [ccyyycy/ycy#276]
只是提创意，大牛来实现。

现在是9102年，杨超越已经成为了大明星，作为一个粉丝，你对挖机的运营非常不满意。

现在你穿越回了2018年2月，进入了挖机公司，成为一名小职员。你要用自己的智慧，送超越mm出道并成为大明星，同时让挖机倒闭。

可能要与疼讯，跃花，问蓝等等公司的人以及挖机的领导打交道。

你有一年的时间。

仿照中国式家长的游戏方式。

**Comment by fzq5201314** [comment]
有风险，不建议
