### ISSUE TITLE
【杨超越商城百天计划】+【oc + swift + dart + java】+【iOS + 安卓 + flutter】+【3-4人 不需要美工】+ 【qq 45329453 问题随便写】

### ISSUE THREAD

**Issue by shabake** [ccyyycy/ycy#297]
【杨超越商城百天计划】+【oc + swift + dart + java】+【iOS + 安卓 + flutter】+【3-4人 不需要美工】+ 【qq群674639629 】

**Comment by shabake** [comment]
【杨超越商城百天计划】+【oc + swift + dart + java】+【iOS + 安卓 + flutter】+【3-4人 不需要美工】+ 【qq674639629 】

**Comment by fanyuexiang** [comment]
你确定是这个群？ 群号明明是技术胖的flutter群啊？

**Comment by ZHBoy** [comment]
对呀，这不是技术胖的flutter群吗
