### ISSUE TITLE
【游戏】+【拯救村花超越】+【微信小游戏/html5游戏】+【1人】

### ISSUE THREAD

**Issue by dengqinghai** [ccyyycy/ycy#307]
你和村花超越在村子里玩耍的时候，突然出现一个自称为“阿三飞侠”的人抓走了，作为村民的你为了就村花踏上了一条不归路，可是最后才得知事情不是这么简单。。。

**Comment by dengqinghai** [comment]
现在就一个人，有画师想要加入的请在下方留言，没人的话就算了

**Comment by SongZihuan** [comment]
还在吗？想组队
