### ISSUE TITLE
【游戏】+【歪西歪向前冲(音乐H5小游戏类似音速)】+【H5移动端】+【未定】

### ISSUE THREAD

**Issue by mr-liuliang** [ccyyycy/ycy#35]
只是一个想法，因为以前喜欢玩《QQ音速》，想自己做一个小点的乐一乐。

PVE就只有打歌模式，歌曲使用超越相关的歌曲。PVP有对战模式和道具模式，歌曲沿用PVE并加上比较经典的歌。先做PVE有精力时间再做PVP，PVE也只专注“打歌”过程，其他简易做。

人物模型的话女生使用Q版超越，男生使用金毛Q版超越，相关人物动画要参考超越沙雕日常哈哈。界面UI参考QQ音速自制单机win版。

小弟这只是个想法，可供参考，如果有大佬想带带我也是极好。本人刚入H5游戏还没有一年，缺乏技术经验积累，最近组长要离职了，我们手底下的人要接手代码熟悉，可能没时间参加比赛了，大家加油！

**Comment by huangluoxi312** [comment]
这个感觉蛮有意思的

**Comment by wzsz29** [comment]
感觉挺有意思的，但是成果怎么呈现呢？难道整一篇论文出来
