### ISSUE TITLE
【游戏】+【杨超越的试炼】+【web前端】+【1~3人（已满）】+【qq：3319295406】

### ISSUE THREAD

**Issue by cxchhh** [ccyyycy/ycy#375]
杨超越H5页游

**Comment by cxchhh** [comment]
有熟悉web前端的尽快加入吧！

**Comment by Redspitee** [comment]
我要来！加你qq了

**Comment by cxchhh** [comment]
目前的代码+素材

[ycy.zip](https://github.com/ccyyycy/ycy/files/2957175/ycy.zip)

**Comment by cxchhh** [comment]
最终成品
[#375 杨超越的试炼 functionUndefined.zip](https://github.com/ccyyycy/ycy/files/3026458/375.functionUndefined.zip)
[ycy.zip](https://github.com/ccyyycy/ycy/files/3026459/ycy.zip)
