### ISSUE TITLE
【平台】+【寄忆】+【缺人】+【QQ：3305753065（需要UI，iOS端，安卓端，web端，小程序端，手表端等【包括前后端】）】

### ISSUE THREAD

**Issue by SuperH-0630** [ccyyycy/ycy#386]
这是一款结合超越的日志记录社交软件。这款软件最大的特点在于每一位用户都可以分享日志,包括文字、照片和语音留言,而且每位用户发布的日志被刷新的几率相等,这使每位软件用户都可以看到其它用户所分享的日志,在文字、图片和声音中感受世界之美。并且该软件拥有强大的导出功能,用户的每一篇日志
都可以导出到本地。而且用户无论什么时候都可以在数据库下载自己的日志,永存美好的记
忆。软件采用人工智能管理,主要用于日志、回复等审核和简短日志的生成等。

**Comment by SongZihuan** [comment]
我只是可视化编程的小白，逻辑虽强大，但是没有敲代码的经验。如果想组队直接加QQ，随时欢迎，目前需要：美工（素材设计）+策划（创意设计），当然，如果如果你不是美工，也不会策划，也欢迎你的加入哦。（PS：欢迎前来投（guang）稿（gao）、内测），现在还需要iOS端和硬件设计师哈

**Comment by SongZihuan** [comment]
谁都可以，现在缺人
