### ISSUE TITLE
【即时通讯】+【超越专属“微信”】+【2 人已满】+ 【imndxx@gmail.com】

### ISSUE THREAD

**Issue by imndx** [ccyyycy/ycy#399]
创建一套超越专属即时通讯解决方案，主要特性：
1. 支持各种消息。
2. 音视频功能。
3. 万人粉丝群。
4. 超越专属表情。

**Comment by SongZihuan** [comment]
可以提供QQ或者微信吗

**Comment by imndx** [comment]
@SuperH-0630 QQ是：2377468043

**Comment by SongZihuan** [comment]
好的

**Comment by imndx** [comment]
鉴于，未报名成功，直接把我们的base作品公布吧。

[野火IM解决方案](https://github.com/wildfirechat)

**Comment by heavyrain2012** [comment]
贴一个野火IM的应用gif吧，本来是有机会做成一个超越专属微信的，logo/启动页和表情全是超越的，可惜没有报上名
![野火IM](https://camo.githubusercontent.com/11db452b68387f890ab59434c22227a9b8ed25c8/687474703a2f2f7374617469632e77696c6466697265636861742e636e2f696f732d64656d6f2e676966)
