### ISSUE TITLE
逐梦演艺圈---身体变成进军演艺圈的本钱

### ISSUE THREAD

**Issue by lcllge** [ccyyycy/ycy#40]
可以开发一个,让广大少女怀有春梦的筑梦演艺圈推送热门头条模块,可以靠身体换取酬劳,一起为了和谐共赢的出道加油!!!

**Comment by podiumdesu** [comment]
请定义一下「靠身体换取酬劳」的意思

**Comment by lcllge** [comment]
就是卖唱啊,喝酒啊啥的,能力第一,能干不能干,全靠身体赚
