### ISSUE TITLE
中国式出道

### ISSUE THREAD

**Issue by likunqiao097304** [ccyyycy/ycy#41]
主要针对超越妹妹的努力成长史，兼顾学习技能， 跳舞和种菜

**Comment by fzq5201314** [comment]
请大家在issue发表组队需求时参照本文
标题：【大致方向】+【名称】+【相关技术/平台】+【组队所需人数】
例子：【游戏】+【村民月芽大战黑子小游戏】+【微信小程序】+【3人】
内容：写明本项目的最终目标，实现方式，初步想法，以及联系方式/群内ID等

希望尽快更改哦
