### ISSUE TITLE
【爬虫方向】+【issue里大家对爬虫的需求挺高的, 希望大家可以聚到一起, 群策群力, 做一个大项目出来】+【python】+【多多益善】

### ISSUE THREAD

**Issue by slimwang** [ccyyycy/ycy#42]
>先简单介绍一下我之前做过的东西:
>* [Sheepdog](https://github.com/slimwang/sheepdog): 一个对新浪微博用户进行情绪分析的项目, 可以实时爬取特定微博用户的最新微博, 并对其进行情绪分析, 当其出现极端情绪时, 会自动向我的手机发一条通知短信 
>*  [Cet4-6](https://github.com/slimwang/cet4-6): 还有一个大学英语四六级的爬虫, 可以爬取全校学生四六级成绩
>* 全栈工程师实习经验

我看issue里爬虫相关的idea挺多的, 然后我就想, 咱们能不能聚到一起, 聊一聊, 来一次头脑风暴, 然后共同做出一个不错东西出来. 

目前是打算建一个微信群或者qq群(qq群加起来比较方便), 大家先沟通一下, 形成一个大致的方向和思路.
* ~~希望能有个高贵的QQ会员来建一个QQ群, 然后贴在下面~~ 
* **QQ群已建好:** 225712381
* 欢迎各位技术大佬的加入
* 也欢迎对技术不太了解的萌新进来交流, 活跃气氛, 并提供一些新想法和新思路
* 特别欢迎有学习热情的同学们, 通过自学来为这个项目作出贡献

**Comment by h-peng17** [comment]
赞同，我就是什么都不熟练的同学

**Comment by huanghaoding** [comment]
作为还没毕业的学生党，平时写爬虫都是自己玩玩。。。真正复杂的爬虫还真没做过

**Comment by LiqiQi0** [comment]
可以，我觉得爬虫类的可以专门组个组。

**Comment by dogexu** [comment]
有大佬建群了吗？可已leave一个方式让我这个小白进去学习下否？

**Comment by Superbsco** [comment]
前端，回点java和python，大佬拉我

**Comment by xingxishen** [comment]
java会点爬虫行不

**Comment by CoderMrD** [comment]
怎么加入呢，会python和js，在职

**Comment by Empty-S** [comment]
本人有个做平台的想法，可以给你们提供个idea...但是自己没时间做...可以结合@yunyingtu 提供的issue32里的村民动态掌握和@newlightlw 提供的issue33里的反黑，以及其他一些和爬虫有关的我看群里@Liquid(QQ群)提到的粉丝构成等等

**Comment by sai111** [comment]
怎么加入

**Comment by RRRCat** [comment]
坐等高贵的QQ会员

**Comment by qImmIp** [comment]
先组一个微信群？有兴趣的先加我微信:Immestrella，备注Github 杨超越就行 。

**Comment by a462247201** [comment]
没人建我建了啊  225712381  2000人群

**Comment by a462247201** [comment]
> > 先简单介绍一下我之前做过的东西:
> > 
> > * [Sheepdog](https://github.com/slimwang/sheepdog): 一个对新浪微博用户进行情绪分析的项目, 可以实时爬取特定微博用户的最新微博, 并对其进行情绪分析, 当其出现极端情绪时, 会自动向我的手机发一条通知短信
> > * [Cet4-6](https://github.com/slimwang/cet4-6): 还有一个大学英语四六级的爬虫, 可以爬取全校学生四六级成绩
> > * 全栈工程师实习经验
> 
> 我看issue里爬虫相关的idea挺多的, 然后我就想, 咱们能不能聚到一起, 聊一聊, 来一次头脑风暴, 然后共同做出一个不错东西出来.
> 
> 目前是打算建一个微信群或者qq群(qq群加起来比较方便), 大家先沟通一下, 形成一个大致的方向和思路.
> 
> * 希望能有个高贵的QQ会员来建一个QQ群, 然后贴在下面
> * 欢迎各位技术大佬的加入
> * 也欢迎对技术不太了解的萌新进来交流, 活跃气氛, 并提供一些新想法和新思路
> * 特别欢迎有学习热情的同学们, 通过自学来为这个项目作出贡献
> * 我可以负责爬虫部分和 web 开发部分, 如果你对这些东西感兴趣, 我也可以分享下我自学的相关经验

QQ群已建 225712381

**Comment by cdmalcl** [comment]
我弄个微信群：
![python](https://user-images.githubusercontent.com/8749073/59037186-5c3c1900-88a3-11e9-870e-124a5762a84e.jpg)
