### ISSUE TITLE
关于比赛规则

### ISSUE THREAD

**Issue by YahuiLu** [ccyyycy/ycy#5]
之前写在readme里，没有显示，先写到这里，大家继续讨论

第一个阶段，大家在GitHub提交自己的想法，要做什么。可以以issue的方式提出

第二阶段，组队，每队五人，限定时间做demo，将demo提交到repo

第三阶段，评比，选出前三。评比可以按照star或者其他规则，待商量

第四阶段，围绕前三继续投入，做出实用的产品。

**Comment by YahuiLu** [comment]
之前我也想着是acm刷题的方式来比赛，后来觉得还是做一些小项目比较有意义

对于项目没有限制，唯一要求是和杨超越相关

**Comment by hejujie** [comment]
希望重点不在于过高的技术含量，而是怎么样便利村民们的追星日常，减少工作组的工作量，或者提供趣味，这样才显得不是大家在自嗨。
