### ISSUE TITLE
【区块链游戏】+【加密杨超越】+【区块链/ETH/NEO/EOS】+【1-3人】

### ISSUE THREAD

**Issue by ProDog** [ccyyycy/ycy#69]
在区块链上以智能合约形式发布一款加密资产，类似以太坊上的加密猫等、可以用加密杨超越作为主题。

**Comment by Little-kwy** [comment]
+1

**Comment by fzq5201314** [comment]
如果只是模仿加密猫，感觉创意不太够啊

**Comment by ProDog** [comment]
> 如果只是模仿加密猫，感觉创意不太够啊

可以增加许多有创意的东西，比如互相PK、技能值属性、衣服妆容等都作为属性。

**Comment by yasongxu** [comment]
+1，之前群里也发了这个，没人理我

**Comment by ZhouFyk** [comment]
这个靠谱点  刚刚看到一个区块链整套生态开发的 吓到我

**Comment by lovelychenlin** [comment]
缺人吗？我搞过区块链，想加入

**Comment by lalalallzx** [comment]
还缺人么,这边两个人求打包

**Comment by lalalallzx** [comment]
还缺人么,这边两个人求打包

**Comment by ProDog** [comment]
缺：1个设计/UI、1个前端、1个后端/区块链/智能合约开发。

**Comment by IsDxxxM** [comment]
> 缺：1个设计/UI、1个前端、1个后端/区块链/智能合约开发。

楼主还缺人么，可以支持做后端
