### ISSUE TITLE
【APP找你妹游戏】+【拯救杨超越】+【Android/后端】+【3-5】+【QQ：384980959】

### ISSUE THREAD

**Issue by gs666** [ccyyycy/ycy#81]
大概就是做一个类似“找你妹”的游戏，游戏有不同的级别，比如从10个图里找到杨超越，20、30、---100等，然后可能需要后端来个服务器整个全球排名之类的，本人是 Android 一枚，希望再来个 Android、后端~

**Comment by qbw2006** [comment]
java后端。WX:tangjunaiwo

**Comment by jinghuihai** [comment]
Android，希望能帮忙做点东西

**Comment by zhangsheng1992** [comment]
golang后端  wx:zhangsheng_1992

**Comment by gs666** [comment]
> Android，希望能帮忙做点东西

大家都留的微信，那就留个微信吧

**Comment by jinghuihai** [comment]
> > Android，希望能帮忙做点东西
> 
> 大家都留的微信，那就留个微信吧

2636658250

**Comment by dongjingfu** [comment]
java后端WX:fu894249308

**Comment by GudthliyaHonor** [comment]
如果追求效率什么的。PHP后端想略尽绵薄之力。WX：121244298

**Comment by imisswkq** [comment]
我觉得你还需要一枚iOS wx:a609980487

**Comment by huashazhuoying** [comment]
Android、 java后台 微信：Only_baby_26
