### ISSUE TITLE
【工具】+【月芽月记】+【微信小程序】+【1人】

### ISSUE THREAD

**Issue by fangkexin** [ccyyycy/ycy#86]
制作一个记录月芽月经记录的 日记型小程序 类似于美柚  预计开发周期14个工作日
参与人1人  联系方式微信：fkx5521  微信群：杨超越杯编程大赛讨论群 群内id：PHP词穷！

**Comment by fangkexin** [comment]
> 制作一个记录月芽月经记录的 日记型小程序 类似于美柚
 预计开发周期5-7个工作日
> 参与人1人 联系方式微信：fkx5521 微信群：杨超越杯编程大赛讨论群 群内id：PHP词穷！

**Comment by fzq5201314** [comment]
涉及不良言论，close
